language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-27

script:
- make build-release

after_success:
  # deploy snapshot artifacts to sonatype
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "release to maven central";

        # Echo username and password into gradle.properties
        # This will be picked up in gradle/mvn-push-android.gradle
        echo "NEXUS_USERNAME=$CI_DEPLOY_USERNAME
        NEXUS_PASSWORD=$CI_DEPLOY_PASSWORD" >> gradle.properties

        make publish
    else
        echo "Not deploying artifacts for $TRAVIS_BRANCH";
    fi